version: '3'

services:

  app:
    build:
      context: docker/php
    restart: 'no'
    volumes:
      - ./:/var/www/app:cached

  nginx:
    build:
      context: docker/nginx
    restart: 'no'
    links:
      - app
    ports:
      - 80:80
